### ISSUE TITLE
Feature: Allow deploying the transaction with a relative path.

### ISSUE THREAD

**Issue by satyamakgec** [onflow/flow-js-testing#100]
### Issue To Be Solved

There are many cases where transactions are scripts are in different folders, Specifically, during testing, a developer may need to write some additional transactions and scripts to support the main transaction because that developer may not put those mock transactions within the designated `transaction`  directory to avoid confusion. To resolve that most of the developers intend to have a mock directory under the `test` directory where those transactions and scripts would reside.

But above is not possible because `flow-js-testing` framework does not allow deploying the transactions using the name from the other directory besides the `transaction` that lives parallel to the `contracts`. Because of this testing, a complex project is not feasible. 

### Possible Solution

I suggest allowing transactions to be deployed using the relative path given during the deployment to resolve the above.

**Comment by jribbink** [comment]
This issue was resolved in #51.  `init(basePath, props = {})` allows for the passing of either a string for a default base path for all cadence, or the passing of an object of the form:

```javascript
const basePath = {
    scripts  // scripts base path, resolves to `${basePath.scripts}/${name}.cdc`,
    transactions  // transactions base path, resolves to `${basePath.transactions}/${name}.cdc`,
    contracts  // contracts base path, resolves to `${basePath.contracts}/${name}.cdc`,
    base // fallback base path if path was not provided for type, resolves to `${basePath.base}/${type}/${name}.cdc`
}
```
