### ISSUE TITLE
Feature: Allow blocktimestamp jump in emulator for better testing.

### ISSUE THREAD

**Issue by satyamakgec** [onflow/flow-js-testing#101]
### Issue To Be Solved

Currently jumping the block number is possible but jumping the block timestamp is not possible that would be needed to test transactions which fail if they get executed after a certain interval of time, More like because of the expiry of operation.

### Suggest A Solution

Introduce a utility function like `setBlockOffset` called `setTimestampOffset` to resolve the above.

**Comment by refi93** [comment]
@jribbink I see you assigned yourself this issue, this PR should fix it: https://github.com/onflow/flow-js-testing/pull/126 - could you please review it?
