### ISSUE TITLE
Address replacement functionality is prone to mistakes

### ISSUE THREAD

**Issue by bartolomej** [onflow/flow-js-testing#104]
### Instructions

I have followed the instructions for setting up the development environment. I'm using flow-js-testing along with jest for testing smart contract functionality.

### Problem

I wanted to read some script/transaction/contract code and replace some addresses specified in `addressMap`.

Cadence source code looked something like this:

```cadence
import SomeContract from SomeContractAddress
```

I tried to read the source code with flow-js-testing like this:
```js
const code = await getTemplate(
      "./cadence/path/to/code.cdc,
      { SomeContractAddress: "0xf8d6e0586b0a20c7" }
);
```

However the result that I received looked like this:

```cadence
import SomeContract from undefined
```

I finally realized that I needed to declare the cadence code in this way:
```cadence
import SomeContract from SmartContract
```
And then read it like this:
```js
const code = await getTemplate(
      "./cadence/path/to/code.cdc,
      { SomeContract: "0xf8d6e0586b0a20c7" }
);
```

I think that the usage of templates needs to be better explained in [the documentation](https://docs.onflow.org/flow-js-testing/templates/). 

Also if the source code contains a line with a pattern that should be replaced and the user doesn't provide that key in the address map, the function should return some kind of error to inform the user about his/her mistake.

### Steps to Reproduce

Provide an address key in cadence code instead of providing an actual address, then provide an empty `addressMap` or do not include the needed key.

### Context

I'm trying to test smart contract functionality.

**Comment by MaxStalker** [comment]
The problem was not in how you write import statement, but in how you prepare your `addressMap` :)
`addressMap` need to be an object, where each key is the `name of the contract` and each value is the `address`, where corresponding contract is deployed.

Your import statements could be in those forms:
```cadence
import Basic from 0x01
import Advanced from 0x02
```
or 
```cadence
import Basic from ./cadence/contracts/Basic
import Advanced from ./cadence/contracts/Advanced
```
Your `addressMap` in both cases should be:
```js
{
    Basic: "0x01", // or whatever address, where it will be deployed, during code execution
    Advanced: "0x02"
}
```

**Comment by MaxStalker** [comment]
@bartolomej can you also tell me why you would want to import templates? :)
We export those so you would have flexibility of building your own solutions, but in most of the cases you should be good with `deployContractByName`, `sendTransaction` and `executeScript` methods. Those accept `name` argument and map it to file stored under corresponding folders for ease of use :)

**Comment by MaxStalker** [comment]
Always happy to help!
