### ISSUE TITLE
Add support for custom signers for sendTransaction

### ISSUE THREAD

**Issue by tav** [onflow/flow-js-testing#154]
### Issue To Be Solved

It would be great if the `signers` for `sendTransaction` could specify the key ID, private key value, as well as support `secp256k1` keys with specific hash functions.

### Suggest A Solution

In addition to a `signer` value being a string address, also support it as an object that can specify the `privateKey`, `keyType`, `keyId`, and `hashAlgorithm`.

### Context

* We rotate keys within our Cadence code, and need to be able to sign with more than just the default `0` key ID.

* We use `secp256k1` keys within our key management systems, and our Cadence code expects keys of this type.

**Comment by jribbink** [comment]
Hey @tav, this should now be available in the latest alpha.  Sorry about the delay.

**Comment by tav** [comment]
Thanks @jribbink — much appreciated!
