### ISSUE TITLE
Support for testing transactions with optional array of Addresses as a parameter

### ISSUE THREAD

**Issue by bymi15** [onflow/flow-js-testing#163]
### Issue To Be Solved
Testing transactions with an optional array of Addresses as a parameter results in the following error:
```
thrown: "[Address]? is not supported"
```

### Context

Example use cases of this type of parameter could be to pass in an allowlist, which can be optional as a nil value would represent the absence of an allowlist and hence allow everyone/anyone.

Discord discussion thread:
https://discord.com/channels/613813861610684416/1004469080268492950

**Comment by jribbink** [comment]
This is a https://github.com/onflow/flow-cadut issue.  Linked issue is https://github.com/onflow/flow-cadut/issues/112

**Comment by jribbink** [comment]
Alright PR is in https://github.com/onflow/flow-cadut/pull/113, awaiting approval, release.  Then needs dependency update on @onflow/flow-js-testing

**Comment by bymi15** [comment]
Thanks a lot for your work @jribbink

**Comment by jribbink** [comment]
Should be solved in latest alpha.  Cheers.
