### ISSUE TITLE
Mock and/or wait for Emulator block height to run test commands

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-js-testing#183]
### Issue To Be Solved

For testing purposes, it would be helpful to have the ability to wait until a certain block to execute a command.

Context

Working on tests & setting conditionals on `getCurrentBlock().height` and finding it difficult to setup tests to properly account for all cases without the ability to wait for a certain block or mock emulator block height.

**Comment by MaxStalker** [comment]
It's possible to mock specific block height 😉 
Here's example on how to do it:
https://github.com/onflow/flow-js-testing/blob/master/examples/07-block-offset.test.js
