### ISSUE TITLE
v0.3.0-alpha.16 inoperable with likely RegExp bug affecting imports

### ISSUE THREAD

**Issue by ph0ph0** [onflow/flow-js-testing#191]
### Instructions

Please fill out the template below to the best of your ability and include a label indicating which tool/service you were working with when you encountered the problem.

### Problem

All tests fail with:

`[Error Code: 1101] cadence runtime error Execution failed:\n' +
        'error: [Error Code: 1054] location (./MetadataViews.cdc) is not a valid location: expecting an AddressLocation, but other location types are passed`

This error occurs when calling any transaction.

Could be an issue with RegExp not matching properly.

### Steps to Reproduce

Ensure version is `@onflow/flow-js-testing@0.3.0-alpha.16`

Run any test that involves a transaction that uses imports. 

### Acceptance Criteria

<if any>

### Context

Testing of project

**Comment by liofancraze** [comment]
Hello,
I'm having the same issue when sending transactions. It seems that the framework don't succeed in resolving imports.

**Comment by ph0ph0** [comment]
Flow CLI: 0.41.0
node: v18.9.0
flow-js-testing: @onflow/flow-js-testing@0.3.0-alpha.16

**Comment by bymi15** [comment]
Same problem here.
The issues seems to occur only for the latest version: [v0.3.0-alpha.16](https://github.com/onflow/flow-js-testing/releases/tag/v0.3.0-alpha.16)
I also tested with [v0.3.0-alpha.15](https://github.com/onflow/flow-js-testing/releases/tag/v0.3.0-alpha.15) and that works fine.

**Comment by sisyphusSmiling** [comment]
@gregsantos could this be related to what was seen in #182?

**Comment by jribbink** [comment]
PR #190 will fix this (exact same fix as #186 but with `executeScript` instead of `sendTransaction` this time).

**Comment by adbario** [comment]
Update to the latest version [v0.3.0-alpha.17](https://github.com/onflow/flow-js-testing/releases/tag/v0.3.0-alpha.17), which fixes the issue.
