### ISSUE TITLE
Undefined error with newer versions of flow-cli

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-js-testing#216]
### Problem

Using flow-js-testing with newer versions of flow-cli throws undefined error.

cc: @MaxStalker 

### Steps to Reproduce

Here's where I'm seeing an issue:

Codebase: [onflow/flow-ft](https://github.com/onflow/flow-ft)
flow-js-testing version: 0.4.0
flow-cli version: 0.49.0
OS: MacOS 13.2.1

Running the tests on `master` branch with flow-cli 0.41.2 (as configured in the ci workflow) works just fine, but updating to the latest release of flow-cli (0.49.0) results in broken js tests such as:

```
  ● CoreFeatures › should be able to setup account

    thrown: undefined

      62 |
      63 |   // Before each test...
    > 64 |   beforeEach(async () => {
         |   ^
      65 |     // We do some scaffolding...
      66 |
      67 |     // Getting the base path of the project

      at beforeEach (core_features.test.js:64:3)
      at Object.describe (core_features.test.js:54:1)
```

### Acceptance Criteria

Compatibility with new flow-cli versions, including updated contract import schema (lmk if you'd like this to be a separate issue).

### Context

[Update contract import schema](https://github.com/onflow/flow-ft/issues/132) which requires new version of flow-cli which is incompatible with flow-js-testing. The linked issue is part of a broader scale effort to update core repos with ecosystem-wide dev tooling and suggested best practices.

**Comment by NtTestAlert** [comment]
The reason is an argument used by the lib (--skip-version-check) is no longer supported

Workaround:
```
// Fix emulator
jest.mock('child_process', () => {
  const original = jest.requireActual('child_process');
  const spawn = (command, args)=>{
    if(command === 'flow' && args?.[0] === 'emulator'){
      return original.spawn(command, args.filter(arg => arg !== '--skip-version-check'));
    }
    return original.spawn(command, args);
  };

  return {
    ...original,
    spawn,
  };
});

```

Easy fix probably. Might create a PR later.

**Comment by jribbink** [comment]
outdated/fixed
