### ISSUE TITLE
Stable Cadence preview release support

### ISSUE THREAD

**Issue by sisyphusSmiling** [onflow/flow-js-testing#224]
## Description

With the Stable Cadence milestone approaching (Cadence 1.0) and preview releases of Flow CLI, emulator, flow-go SDK, etc. enabling devs to compose next version Cadence code, developers will need to be able to test their updated implementations using existing tests.

## Suggestion

This testing framework is often used across many Flow projects, including standard and core repos - flow-nft, nft-storefront, flow-core-contracts to name a few. It would be very helpful to run the same tests passing with a current Cadence version against an updated Cadence 1.0 implementation using a flow-js-testing pre-release.

## Context

Working on [stable cadence updates](https://github.com/onflow/nft-storefront/pull/89) to the NFTStorefront contracts and will continue to update contracts moving forward.

**Comment by NtTestAlert** [comment]
Working on it. Planning on posting a PR tomorrow.
(Currently mocking it with jest internally, will copy over changes upstream)

**Comment by jribbink** [comment]
We will also need to setup a release process/separate branch/CI actions for this functionality.  I will create a `feature/stable-cadence` branch which releases to `@onflow/flow-js-testing@cadence-v1.0.0`.

**Comment by jribbink** [comment]
`@onflow/flow-js-testing@stable-cadence.1` has all of the latest Cadence 1.0 changes
