### ISSUE TITLE
Issue using getAccountAddress

### ISSUE THREAD

**Issue by Luze26** [onflow/flow-js-testing#234]
When using flow-js-testing 0.6.0-stable-cadence.3 and the CLI v1.15.0-cadence-v1.0.0-preview.13.

When I run:
```
await getAccountAddress("Alice");
```

I get the following error:

```
Signatures TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object
        at new NodeError (node:internal/errors:405:5)
        at Function.from (node:buffer:325:9)
        at hashAlgorithm (/tests/node_modules/@onflow/flow-js-testing/src/crypto.js:141:43)
        at Object.signingFunction (/tests/node_modules/@onflow/flow-js-testing/src/crypto.js:191:6)
        at signingFunction (/tests/node_modules/@onflow/sdk/src/resolve/resolve-signatures.ts:59:36)
        at Array.map (<anonymous>)
        at map (/tests/node_modules/@onflow/sdk/src/resolve/resolve-signatures.ts:46:40)
        at processTicksAndRejections (node:internal/process/task_queues:95:5)
        at recPipe (/tests/node_modules/@onflow/sdk/src/interaction/interaction.ts:333:19) {
      code: 'ERR_INVALID_ARG_TYPE'
    } {
      ix: {
        tag: 'TRANSACTION',
        assigns: { 'ix.cadence': [Function (anonymous)] },
        status: 'OK',
        reason: null,
        accounts: { '0xf8d6e0586b0a20c7-0': [Object] },
        params: {},
        arguments: {
          '747260a6-0f25-4a90-a546-8e91e91f3b86': [Object],
          '5f4c855c-d46e-4272-81ac-b43cdb10c37c': [Object]
        },
        message: {
          cadence: '\n' +
            '  transaction(name: String, code: String){\n' +
            '    prepare(acct: auth(AddContract, UpdateContract) &Account) {\n' +
            '      let decoded = code.decodeHex()\n' +
            '      \n' +
            '      if acct.contracts.get(name: name) == nil {\n' +
            '        acct.contracts.add(name: name, code: decoded)\n' +
            '      } else {\n' +
            '        acct.contracts.update(name: name, code: decoded)\n' +
            '      }\n' +
            '    }\n' +
            '  }\n',
          refBlock: 'a20c602fbee6fe4491e116403e3258e7b7924609696ab2edb9a93eed2c29e445',
          computeLimit: 9999,
          proposer: null,
          payer: null,
          authorizations: [],
          params: [],
          arguments: [Array]
        },
        proposer: '0xf8d6e0586b0a20c7-0',
        authorizations: [ '0xf8d6e0586b0a20c7-0' ],
        payer: [ '0xf8d6e0586b0a20c7-0' ],
        events: { eventType: null, start: null, end: null, blockIds: [] },
        subscribeEvents: {
          startBlockId: null,
          startHeight: null,
          eventTypes: null,
          addresses: null,
          contracts: null,
          heartbeatInterval: null
        },
        transaction: { id: null },
        block: { id: null, height: null, isSealed: null },
        account: { addr: null },
        collection: { id: null }
      }
    }

      at error (node_modules/@onflow/sdk/src/resolve/resolve-signatures.ts:48:15)
      at recPipe (node_modules/@onflow/sdk/src/interaction/interaction.ts:333:19)
      at Object.send (node_modules/@onflow/sdk/src/send/send.js:36:5)
```

**Comment by jribbink** [comment]
@Luze26 Does this error still persist after upgrading your Flow CLI?

**Comment by Luze26** [comment]
> @Luze26 Does this error still persist after upgrading your Flow CLI?

Seems like I still have the error.
When running flow-c1 version I get:
`Version: v1.18.0-cadence-v1.0.0-preview.24
Commit: 6aac3b6c7f510feaf7728a48dd8ffa020feb6a0a
`

**Comment by jribbink** [comment]
Hmmm ok, looking into this...

**Comment by jribbink** [comment]
> > @Luze26 Does this error still persist after upgrading your Flow CLI?
> 
> Seems like I still have the error. When running flow-c1 version I get: `Version: v1.18.0-cadence-v1.0.0-preview.24 Commit: 6aac3b6c7f510feaf7728a48dd8ffa020feb6a0a `

I'm having trouble reproducing the issue.  Can you post the node.js version that you are using?  Wondering if this could be related.

**Comment by Luze26** [comment]
> > > @Luze26 Does this error still persist after upgrading your Flow CLI?
> > 
> > 
> > Seems like I still have the error. When running flow-c1 version I get: `Version: v1.18.0-cadence-v1.0.0-preview.24 Commit: 6aac3b6c7f510feaf7728a48dd8ffa020feb6a0a `
> 
> I'm having trouble reproducing the issue. Can you post the node.js version that you are using? Wondering if this could be related.
> 
> Also is there any chance you could post a code snippet of the failing test?

Thx for looking into it.
I tried with node 18 and 20 and got the same error.
I also tried to reproduce it with the basic test that is created running:
```
npx flow-js-testing init
npx flow-js-testing make basic-test
```
I then updated the dependencies to use the stable cadence version of flow-js-testing. And I get the same error, I also get this error with version 0.5.0.
You can find the code here: https://github.com/Luze26/flow-js-testing-bug-repro
I'll try to understand more the issue. Previously we were using the old version of flow-js-testing that could be found here https://www.npmjs.com/package/flow-js-testing , but even when trying the last version of this lib I get the same error

**Comment by Luze26** [comment]
So `privateKey` here https://github.com/onflow/flow-js-testing/blob/1b630d2c9bdd97e30d0b302997ff6c9f2c800d98/src/crypto.js#L140 is equal to the following object
```
{
	"type": "file",
	"location": "emulator-account.pkey"
}
```
So it fails, if I change the config in flow.json to directly include the key it works well.

**Comment by Luze26** [comment]
awesome, thx a lot
