### ISSUE TITLE
Improper path being resolved for cadence 'manager' scripts, transactions and contracts

### ISSUE THREAD

**Issue by aishairzay** [onflow/flow-js-testing#30]
### Problem
Unable to run getAccountAddress and many other functions that interact with the flow emulator without some manual changes. The path to the standard contracts, scripts, and transactions for the 'manager' seem to have been modified in an update, and the corresponding path resolving from within flow-js-testing is referencing the old path.

For reference, I'm on Windows using Git Bash, this may be specific to a windows environments, I'm unsure about this.

Easy way I was able to fix this manually which I did for now:
`cp -r node_modules/flow-js-testing/dist/manager/* node_modules/flow-js-testing/dist/`

### Steps to Reproduce

    "flow-js-testing": "^0.1.9",

```
import { getContractAddress } from "flow-js-testing";

describe.only("Create accounts", () => {
  test("Create Accounts", async () => {
    const Alice = await getAccountAddress("Alice");
  });
});

```
`yarn jest`

### Acceptance Criteria

Path resolving works as expected with the new directory format - or a link is made by default from /dist/scripts to /dist/manager/scripts, etc

**Comment by MaxStalker** [comment]
This was fixed in version `0.1.10`
