### ISSUE TITLE
Test errors and exception in cadence contract by flow-js-testing

### ISSUE THREAD

**Issue by kalitamih** [onflow/flow-js-testing#34]
**Problem**
Test function pre conditions in contract is not completely convenient, because sendTransaction function doesn't return response with error code and error message. This function throws error like a long string. In my case in order to test pre condition we need to write something like this: 
``` javascript
 test("create", async () => { 
    let error;
    try {
      const result = await sendTransaction({
        code: createTransaction,
        args: [   
          ["1623417982.00", t.UFix64],       
        ], 
        signers: [EMULATOR_ACCOUNT],
      });       
    } catch(e) {
      error = e;
    } 
    expect(error).toMatch(/(Start time can't be in the past)/);  
  }); 
```

To test something similar to: 
``` cadence
 pub fun create(
    startTime: UFix64,     
  ): UInt64 {
      pre {             
          startTime > getCurrentBlock().timestamp : "Start time can't be in the past"
      }            
     ....
  }
```

**Comment by MaxStalker** [comment]
What is the version of library you are using? 🤔

**Comment by kalitamih** [comment]
> What is the version of `flow-js-testing` you are using?

0.1.10

**Comment by jribbink** [comment]
Closing as this functionality is currently part of the `shallRevert` jest assertion https://github.com/onflow/flow-js-testing/blob/master/docs/api.md#shallrevertix-message.
