### ISSUE TITLE
Scripts can only return booleans and numbers

### ISSUE THREAD

**Issue by rykdesjardins** [onflow/flow-js-testing#35]
Before anything, I'd like to personally thank the maintainers of this repo. It has been of tremendous help writing our test suite.

I created a [tiny repo](https://github.com/rykdesjardins/flow-js-testing-issue-35) to give a concrete example as well as a [Playground example](https://play.onflow.org/163540c0-6fb1-4da9-a96f-5ab13441cd7c?type=account&id=58c3ab4a-9ab3-491d-bfd6-49a329b22fcb) of how it should look like. 

### Problem

If a script executed using `executeScript` returns something else than a `Bool` or a `UInt_`, the encoder will throw after having executed the script successfully. 

There it no problem returning a `Bool` and a `UInt_` where they both become a Javascript `boolean` and `number` respectively. Anything else will fail. 

### Steps to Reproduce

The most minimalistic example I could come up with is the following : 

```
// RootContract.cdc
pub contract RootContract {
    pub struct RootStruct {
        pub let rootNumber: UInt64;

        init(rootNumber: UInt64) { self.rootNumber = rootNumber; }
    }
}
```

A script like this one will fail using flow-js-testing, but will work with the cli as well as with the playground. It is not good programming practice, but it's really to have a tiny example :

```
// getRootStruct.cdc
import RootContract from "RootContract.cdc"

pub fun main(): RootContract.RootStruct {    
    return RootStruct(rootNumber: 0);
}
```

The Javascript code snippet would look like this : 

```
// rootStruct.test.js
const scriptCode = await getScriptCode({ name : "getRootStruct", addressMap: getAddressMapSomehow() });
const scriptResult = await executeScript({ code : scriptCode, args: [] });

console.log(scriptResult);
```

At the moment, if I try to return anything else than a `Bool` or `UInt_` from the script, I get the following error message : 

```
    failed to encode value: unsupported value: <nil>, <nil>

      at Object.onEnd (node_modules/@onflow/sdk/src/send/unary.js:4:6)
      at node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:24222
      at node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11539
          at Array.forEach (<anonymous>)
      at e.rawOnError (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:11501)
      at e.onTransportHeaders (node_modules/@improbable-eng/grpc-web/dist/grpc-web-client.js:1:9078)
      at NodeHttp.Object.<anonymous>.NodeHttp.responseCallback (node_modules/@improbable-eng/grpc-web-node-http-transport/src/index.ts:36:18)

```

This will also fail if you try to return a `String` like so : 

```
pub fun main() : String {
    return "Hello, World";
}
```

### Acceptance Criteria

Running the exact same thing on the [Flow playground](https://play.onflow.org/163540c0-6fb1-4da9-a96f-5ab13441cd7c?type=account&id=58c3ab4a-9ab3-491d-bfd6-49a329b22fcb) as well as with the cli seems to be working great. 

I imagine a good acceptance criteria would be for the encoder to be able to correctly encode the different data structures available with Cadence. 

### Note
My environment is Ubuntu 21.04, running Node v.14.15.4. I use jest to write our test suite, and start an emulator `beforeAll`, then stop it `afterAll`. Everything else works perfectly. 

I might be able to help out with this one. The repo's code is very, very clean so I might give it a shot.

**Comment by MaxStalker** [comment]
Thank you for your kind words, @rykdesjardins! :bow: 

I have investigated the issue and created a PR for your example here:
https://github.com/rykdesjardins/flow-js-testing-issue-35/pull/1

Basically, the issue you had was due to the fact that "RootContract" was not deployed, thus failing a script.
But framework was not reporting the problem properly. I will try to improve the code around this case in next version.

**Comment by rykdesjardins** [comment]
Thank you for the example correction! That was mildly embarrassing :sweat_smile: 

In our test suite, everything seems to be working fine except when we return structs defined in contracts. The contracts are correctly deployed since the transaction test works great, and they're in the same test environment. It's only the scripts. Maybe we aren't mapping the contracts correctly when executing scripts. Like you mentioned, If the original error is thrown when a contract fails to resolve (due to not being deployed), it is possible the script fails to import the contract because of wrong address mapping (on our end) and throws the reported error.

Thank you again for helping with this! I'll make sure our address mapping is fine. If we're still experiencing the issue, I'll try to come up with a more complete test case. 

Will follow up today :)

**Comment by rykdesjardins** [comment]
Turns out the issue was with accessing a contract property directly from the script instead of going through an accessor. For reference, here's what was causing the issue. 

Provided that the following contract is deployed : 
```
// RootContract.cdc
pub contract RootContract {
    pub struct RootStruct {
        pub let rootNumber: UInt64;
        init(rootNumber: UInt64) { self.rootNumber = rootNumber; }
    }

    pub let assocObject : {String: RootStruct};

    pub fun getRootStructAt(key: String) : RootStruct {
        pre {
            self.assocObject[key] != nil: "No such Root Struct"
        }

        return self.assocObject[key]!;
    }

    init() {
        self.assocObject = {
            "one"   : RootStruct(rootNumber: 1),
            "two"   : RootStruct(rootNumber: 2),
            "three" : RootStruct(rootNumber: 3)
        };
    }
}
```

#### The following script will fail with the reported error message : 
```
import RootContract from "RootContract.cdc"

pub fun main(key: String): RootContract.RootStruct {    
    return RootContract.assocObject[key]!; // Unwrap can panic
}
```

#### But using an accessor will work just fine : 
```
import RootContract from "RootContract.cdc"

pub fun main(key: String): RootContract.RootStruct {    
    return RootContract.getRootStructAt(key: key); // Can panic in precondition if key not found
}
```

## Bottomline 
I thought the error was originating from returning a struct because that struct was stored in a dictionary, and returning it would crash. Turns out the error was accessing that dictionary from the script scope instead of called an accessor method. 

Then, my minimalistic test case wasn't deployed properly and it would trigger the same error message which I thought was confirming that scripts wouldn't return structs properly.

Thanks for taking of your time to help us! Really appreciated.

**Comment by MaxStalker** [comment]
@rykdesjardins thank you for filling the issue properly - it was a pleasure to work on it :smile_cat:
