### ISSUE TITLE
Use generate-code cmd but clean the project folder

### ISSUE THREAD

**Issue by caosbad** [onflow/flow-js-testing#39]
## Instructions

Please fill out the template below to the best of your ability.

### Issue To Be Solved

Clone this repo and install the dependency，then I run run the generate-code cmd in package scripts, that clean the whole folder. 
I use macOS 10.15.2 
node v14.17.0
flow version Version: v0.25.1
yarn v1.22.4

**Comment by MaxStalker** [comment]
hey, @caosbad !
I just tested it with exact setup - works just fine with `npm` and `yarn` 🤷‍♂️

Can you try one more time?

Also, what are you trying to achieve? 🤔
That `generate-code` script  is required only if you want to make changes to smart contracts and transactions related to `FlowManager`.

**Comment by caosbad** [comment]
Okay, I thought that was generate the cadence code to javascript file ,maybe I have misunderstood , Thanks

**Comment by MaxStalker** [comment]
If you want to use the framework for your own project, you need to install it via `npm` or `yarn` rather than cloning this repo :)

And `flow-generate` command is available via `flow-cadut` package:
https://www.npmjs.com/package/flow-cadut

This way you can transform your Cadence code into Javascript bindings :)

**Comment by caosbad** [comment]
Thanks, I have done some alternative solution  for that, using the fcl-dev-wallet authz function and fcl with cadence, implement the transactions and scripts in javascript with no custodian private key ,just like kittyItems .
And I'll check the flow-cadut out, if I can use it in the future.
