### ISSUE TITLE
Dictionnary {UInt32: UInt32} arg Issue

### ISSUE THREAD

**Issue by triptixnft** [onflow/flow-js-testing#54]
### Instructions

sendTransaction arg will not support a dictionary with key as UInt32

expected arg in transaction parameter :  {UInt32: UInt32}
provided arg in js sendTransaction  : {0 : 1, 1 : 1}

As js  object property name is stored as string => "0" : 1, "1" : 1 is passed to the tx and do not match the expected cadence arg

**Comment by MaxStalker** [comment]
@triptixnft  this should now be possible to do now. Please refer example #101 in examples folder :)
