### ISSUE TITLE
Flow-JS Testing Examples & Documentation

### ISSUE THREAD

**Issue by timmymmit** [onflow/flow-js-testing#6]
## Context

Max has created the JS Testing Framework and we need some documentation and examples of how to use it.

## Definition of Done

Documentation on how to use the JS Testing Framework
Example code showing how to use JS Testing Framework

## PR Review 

Who is your Code Partner - @MaxStalker 
Who can provide external eyes - @timmymmit @psiemens

**Comment by 10thfloor** [comment]
WIP here: 
https://github.com/onflow/flow-playground-tutorials/tree/mackenzie/adds-more-tests/lib/javascript

**Comment by balibou** [comment]
Hello, I assume this repo is deprecated and I should focus on flow-go-sdk ?

**Comment by MaxStalker** [comment]
Nope :)
It haven’t got our attention simply because not that many people asked for it and there were other items with higher priority. 
But I plan to get back to it next week.

**Comment by balibou** [comment]
Ah ok great, because we would love to use it for our startup  😅
By the way, I found your repo and this will be my starter for implementing unit tests with Jest, so a big thank you for that 😃
 
https://github.com/MaxStalker/learn-to-flow/blob/
https://github.com/MaxStalker/use-cadence-js-testing
https://github.com/MaxStalker/flow-pixel-heads

**Comment by MaxStalker** [comment]
You can also export any project from Playground and get some basic setup ready :)

**Comment by balibou** [comment]
ah so great ! Thanks !

Also when I generate a flow.json it doesn't work because the mapped properties are not the same than yours in your repo. It sounds that the version of your generated flow.json is deprecated (as far as I understand 😄 ).

new version (not working):
```
{
	"emulators": {
		"default": {
			"port": 3569,
			"serviceAccount": "emulator-account"
		}
	},
	"contracts": {},
	"networks": {
		"emulator": {
			"host": "127.0.0.1:3569",
			"chain": "flow-emulator"
		}
	},
	"accounts": {
		"emulator-account": {
			"address": "f8d6e0586b0a20c7",
			"keys": "7bf981da00b224da7e22726fcb02d5fc6ef79651555fc01984c08c01e55e5836",
			"chain": "flow-emulator"
		}
	},
	"deployments": {}
}
```

old version (working):
```
{
	"host": "",
	"accounts": {
		"service": {
			"address": "f8d6e0586b0a20c7",
			"privateKey": "7bf981da00b224da7e22726fcb02d5fc6ef79651555fc01984c08c01e55e5836",
			"sigAlgorithm": "ECDSA_P256",
			"hashAlgorithm": "SHA3_256",
			"keyType": "hex",
			"keyIndex": 0,
			"keyContext": {
				"privateKey": "7bf981da00b224da7e22726fcb02d5fc6ef79651555fc01984c08c01e55e5836"
			}
		}
	}
}
```

**Comment by MaxStalker** [comment]
@balibou Indeed! 🙈
CLI was recently updated with a lot of new features and new `flow.json` is not backward-compatible.

**Comment by balibou** [comment]
ahah ok I guess we'll have to work with both versions until the test repo is fully compatible 😄
