### ISSUE TITLE
Allow to pass emulator flags

### ISSUE THREAD

**Issue by MaxStalker** [onflow/flow-js-testing#69]
Emulator is expanding day-by-day and instead of rewriting emulator code every time, we can allow to pass flags and their values into `emulator.start` method.

For example, this code update - https://github.com/Peixer/flow-js-testing/commit/545a8889a8a78c04f27601e75aaaf50feee04e70 - could have been possible with simple `emulator.start(port, {"storage-limit": false})`

**Comment by jribbink** [comment]
This was covered by #90
