### ISSUE TITLE
Adopt the new server status interface from Flow emulator

### ISSUE THREAD

**Issue by kerrywei** [onflow/flow-js-testing#72]
### Problem
It is a commonly encountered issue that there are intermittent failures for tests backed by flow-js-testing library, per described in https://github.com/onflow/flow-js-testing/issues/47. 
It turns out the root cause is that there is not a reliable way for processes to check whether the emulator is fully started, hence tests could be run before HTTP/gRPC servers are ready, causing failures. 

### Steps to Reproduce
run the Jest tests in KittyItems repo. 
(note: this has been temporarily addressed per comment https://github.com/onflow/flow-js-testing/issues/47#issuecomment-1006917613)
Some past evidence: 
https://github.com/onflow/kitty-items/runs/4722525285?check_suite_focus=true
https://github.com/onflow/kitty-items/runs/4721609090?check_suite_focus=true
https://github.com/onflow/kitty-items/runs/4720430127?check_suite_focus=true
https://github.com/onflow/kitty-items/runs/4720205583?check_suite_focus=true

### Acceptance Criteria
- Rather than relying on [this logging line](https://github.com/onflow/flow-js-testing/blob/master/src/emulator.js#L108), use the new interface to be introduced in https://github.com/onflow/flow-emulator/issues/111, so that the emualtor.start() function can return a correct Promise which accurately reflects the server status
- notify community members when the fix is out ( [related Discord comment](https://discord.com/channels/613813861610684416/892862426498887721/928750178280800297) )

**Comment by MaxStalker** [comment]
Fixed in #73
