### ISSUE TITLE
allow deployContractByName to accept subfolder values

### ISSUE THREAD

**Issue by timongll** [onflow/flow-js-testing#86]
Currently blocked to have subfolders in cadence/contracts

For example, 
`return deployContractByName({ to: KittyAdmin, name: 'fungibletoken/FlowToken' })`
does NOT work, resulting in error
`error: invalid contract: the name argument must match the name of the declarationname argument: \"fungibletoken/FlowToken\", declaration name: \"FlowToken\"`

**Comment by timongll** [comment]
@MaxStalker here was the issue I opened

**Comment by MaxStalker** [comment]
@timongll please, try version `0.2.3-alpha.6` it should fix the issue :)

**Comment by timongll** [comment]
thanks works now!
