### ISSUE TITLE
Account creation name has been changed from "AccountAdded" to "AccountCreated"

### ISSUE THREAD

**Issue by mrakus7** [onflow/flow-js-testing#87]
$ flow version
Version: v0.31.1
Commit: a622a4f89a4a86c4edb0161d8df3316345f2fb93

The name of event for new account creation has been changed from "AccountAdded" to "AccountCreated"

Perhaps, more better to get this constant from some Flow constant vocabulary?

Issue in line:
https://github.com/onflow/flow-js-testing/blob/f19756f0ee9e00c096233a9cd89ee10cd3a1f7e8/src/account.js#L63

**Comment by MaxStalker** [comment]
@mrakus7 as a matter of fact - that is a correct event name. Since we are not using global system event, but custom one emitted by account manager, which is used by the library.
