### ISSUE TITLE
run `npm test` got an "thrown undefined" error at `beforeEach`

### ISSUE THREAD

**Issue by swordc** [onflow/flow-js-testing#94]
<img width="509" alt="image" src="https://user-images.githubusercontent.com/6340093/157885144-a6fe92a6-ecc7-4a01-9aa4-b347b59f2b75.png">
It passed if running `npm test xxxx.test.js` separately.
However, when running `npm test` together the error occurred.

Version: v0.31.1 - 0.2.3-alpha.3/4

**Comment by onkel-skrue** [comment]
Getting:
```
npx jest                                                                                                                                                                                                                                                22-03-19 - 14:44:52
  console.error
    stderr: Error: unknown flag: --http-port
 ```
 
 with 
 ```
const port = 7002;
await init(basePath, { port });
await emulator.start(port, true);
```

Should be `--rest-port` instead of `--http-port`. 

```
flow emulator -h | grep 'port'                                                                                                                                                                                                                          22-03-19 - 14:48:47
      --admin-port int                  port to run the admin API (default 8080)
      --dev-wallet-port int             port to run Dev Wallet server (default 8701)
  -p, --port int                        port to run RPC server (default 3569)
      --rest-port int                   port to run the REST API (default 8888)
```

**Comment by onkel-skrue** [comment]
I just noticed that updating to `"@onflow/fcl": "0.0.78"` fixed the problem for me.

**Comment by swordc** [comment]
> I just noticed that updating to `"@onflow/fcl": "0.0.78"` fixed the problem for me.

Still have the same issue with "@onflow/fcl": "0.0.78"

**Comment by onkel-skrue** [comment]
> Still have the same issue with "@onflow/fcl": "0.0.78"

Try to run with logs enabled: `await emulator.start(port, true)` and see what you get

**Comment by MaxStalker** [comment]
What is your CLI version?

**Comment by swordc** [comment]
> What is your CLI version?

Version: v0.31.1

> Try to run with logs enabled: `await emulator.start(port, true)` and see what you get

Have opened the log and got undefined errors.
<img width="615" alt="image" src="https://user-images.githubusercontent.com/6340093/159433865-d57cbcbf-9da0-4cca-a570-5bfd9a9523db.png">

**Comment by kerrywei** [comment]
@MaxStalker  if we find out the root cause, in addition to address it, I think we should summarize it and post it here for future references; we should also include the answer to "what can we do to eliminate this in future" in the summary, if applicable

**Comment by MaxStalker** [comment]
@swordc @onkel-skrue can you guys try to update version to `0.2.3-alpha.5` and run your tests?

**Comment by dryruner** [comment]
@MaxStalker Still have the same "thrown undefined" problem if running `$ npm run test`

However, if I run test 1-by-1 e.g. `$ npm test tests/test/sample.test.js`, all of them pass.

CLI: 
Version: v0.36.0
Commit: dffa320324766cb87a55cbf9db2223038cb7b0df

flow-js-testing:
^0.2.3-alpha.5

**Comment by onkel-skrue** [comment]
> @MaxStalker Still have the same "thrown undefined" problem if running `$ npm run test`
> 
> However, if I run test 1-by-1 e.g. `$ npm test tests/test/sample.test.js`, all of them pass.
> 
> CLI: Version: v0.36.0 Commit: dffa320324766cb87a55cbf9db2223038cb7b0df
> 
> flow-js-testing: ^0.2.3-alpha.5

Do you run `jest --runInBand`?

**Comment by dryruner** [comment]
@onkel-skrue Ah just tried with the flag, all tests run successfully. Thanks!

One more question: this flag runs test files in a sequantial way, I remember previously that jest can run test files concurrently (without appending any flag) - is there still a way to do so?

**Comment by onkel-skrue** [comment]
> @onkel-skrue Ah just tried with the flag, all tests run successfully. Thanks!
> 
> One more question: this flag runs test files in a sequantial way, I remember previously that jest can run test files concurrently (without appending any flag) - is there still a way to do so?

Glad it solved the problem :) I don't really know the answer to your question. I am just running with this flag for now.
