### ISSUE TITLE
panic message cannot have "transaction" word in it

### ISSUE THREAD

**Issue by Guisong-Fu** [onflow/flow-js-testing#97]
### Problem

panic message cannot have "transaction" word in it, otherwise it will throw "undefined is not supported" error.

### Steps to Reproduce

Basically, add "transaction" word to the panic message, and use js-testing to run the test against it, the error will be reproduced.

Take kitty-item for example, locate the script `get_collection_length.cdc` and update the panic message to something like this

`
let collectionRef = account.getCapability(KittyItems.CollectionPublicPath)!
    .borrow<&{NonFungibleToken.CollectionPublic}>()
    ?? panic("transaction")
`

And run the test suite, the error will be re-produced.

### Acceptance Criteria

Be able to include "transaction" word in the panic message.

### Context

Maybe it's good to also mention what transaction the user needs to send in the panic message.

For example, I want to have panic message like this "you would need to send the SetUp Account transaction first"

**Comment by jribbink** [comment]
This should be resolved in @onflow/flow-js-testing@0.3.0-alpha.10
